---
name: "simple github action"

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip
          unzip terraform_*.zip
          sudo mv terraform /usr/local/bin/
          rm terraform_*.zip
        shell: bash
      - name: "running date command"
        run: date
        shell: bash

      - name: "getting os details"
        run: cat /etc/os-release
        shell: bash

      - name: "user details"
        run: whoami
        shell: bash

      - name: "current working before directory"
        run: |
          pwd
          ls -al

      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "current working after directory"
        run: |
          pwd
          ls -al

      - name: "running script"
        run: |
          chmod +x script.sh
          ./script.sh

